name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: Tests
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}
    env:
      working-directory: ./bmp180
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
        
      - name: Check formatting
        working-directory: ${{env.working-directory}}
        run: cargo fmt -- --check

      - name: Check for clippy warnings
        working-directory: ${{env.working-directory}}
        run: cargo clippy --all --all-features -- -D warnings
        
      - name: Run tests
        working-directory: ${{env.working-directory}}
        run: cargo test --all-features
